### ISSUE TITLE
Can you give me advice for modeling ? 

### ISSUE THREAD

**Issue by NKYoon** [10Andrea10/PowerCubeSat#1]
I compared with your code and SPATpro program. Two programs give the different result
![image](https://user-images.githubusercontent.com/19286796/220552015-9e2dbefe-4e27-4d83-9eda-1ae2cc2a11cd.png)
this result is the SPATpro program. 

![image](https://user-images.githubusercontent.com/19286796/220552115-129556a2-c99a-4005-927a-ce1e0aec9f1e.png)
This is the PowerCubeSat-master code result. 

![image](https://user-images.githubusercontent.com/19286796/220552249-fe51ce9f-c2a4-4044-a839-9cc5f9a9d1e5.png)
This is my geometry. 

Please give me some adive about the **different result**. 

one more thins is I want to see the bleow figure. Can you add this function ? 
![image](https://user-images.githubusercontent.com/19286796/220552805-7238aeb6-8e49-4af4-905c-3c28dc4ebb5c.png)

Thank you .

**Comment by NKYoon** [comment]
![image](https://user-images.githubusercontent.com/19286796/222376487-e6b41ff7-d123-456a-a07b-deb5d7bd1046.png)
How Can I select appropriate value ?

**Comment by 10Andrea10** [comment]
Hi @NKYoon , unfortunately I’m not maintaining this repo anymore.
